/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminServicosRouteImport } from './routes/admin.servicos'
import { Route as AdminRelatoriosRouteImport } from './routes/admin.relatorios'
import { Route as AdminRegrasRouteImport } from './routes/admin.regras'
import { Route as AdminPropostasRouteImport } from './routes/admin.propostas'
import { Route as AdminPipelineRouteImport } from './routes/admin.pipeline'
import { Route as AdminPendentesRouteImport } from './routes/admin.pendentes'
import { Route as AdminImportarRouteImport } from './routes/admin.importar'
import { Route as AdminDfcRouteImport } from './routes/admin.dfc'
import { Route as AdminContratosRouteImport } from './routes/admin.contratos'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as ConfigurarAcessoRouteImport } from './routes/configurar-acesso'
import { Route as AdminPropostasIndexRouteImport } from './routes/admin.propostas.index'
import { Route as AdminContratosIndexRouteImport } from './routes/admin.contratos.index'
import { Route as PPropostaTokenRouteImport } from './routes/p.proposta.$token'
import { Route as AdminPropostasNovaRouteImport } from './routes/admin.propostas.nova'
import { Route as AdminInsightsPrecificacaoRouteImport } from './routes/admin.insights.precificacao'
import { Route as AdminContratosNovoRouteImport } from './routes/admin.contratos.novo'
import { Route as AdminClientesClientIdRouteImport } from './routes/admin.clientes.$clientId'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicosRoute = AdminServicosRouteImport.update({
  id: '/admin/servicos',
  path: '/admin/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/admin/relatorios',
  path: '/admin/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRegrasRoute = AdminRegrasRouteImport.update({
  id: '/admin/regras',
  path: '/admin/regras',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPropostasRoute = AdminPropostasRouteImport.update({
  id: '/admin/propostas',
  path: '/admin/propostas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPipelineRoute = AdminPipelineRouteImport.update({
  id: '/admin/pipeline',
  path: '/admin/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPendentesRoute = AdminPendentesRouteImport.update({
  id: '/admin/pendentes',
  path: '/admin/pendentes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImportarRoute = AdminImportarRouteImport.update({
  id: '/admin/importar',
  path: '/admin/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDfcRoute = AdminDfcRouteImport.update({
  id: '/admin/dfc',
  path: '/admin/dfc',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContratosRoute = AdminContratosRouteImport.update({
  id: '/admin/contratos',
  path: '/admin/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/admin/clientes',
  path: '/admin/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/admin/categorias',
  path: '/admin/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurarAcessoRoute = ConfigurarAcessoRouteImport.update({
  id: '/configurar-acesso',
  path: '/configurar-acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPropostasIndexRoute = AdminPropostasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPropostasRoute,
} as any)
const AdminContratosIndexRoute = AdminContratosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminContratosRoute,
} as any)
const PPropostaTokenRoute = PPropostaTokenRouteImport.update({
  id: '/p/proposta/$token',
  path: '/p/proposta/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPropostasNovaRoute = AdminPropostasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AdminPropostasRoute,
} as any)
const AdminInsightsPrecificacaoRoute =
  AdminInsightsPrecificacaoRouteImport.update({
    id: '/admin/insights/precificacao',
    path: '/admin/insights/precificacao',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminContratosNovoRoute = AdminContratosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AdminContratosRoute,
} as any)
const AdminClientesClientIdRoute = AdminClientesClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => AdminClientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/configurar-acesso': typeof ConfigurarAcessoRoute
  '/admin/clientes': typeof AdminClientesRouteWithChildren
  '/admin/contratos': typeof AdminContratosRouteWithChildren
  '/admin/dfc': typeof AdminDfcRoute
  '/admin/importar': typeof AdminImportarRoute
  '/admin/pendentes': typeof AdminPendentesRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/propostas': typeof AdminPropostasRouteWithChildren
  '/admin/regras': typeof AdminRegrasRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/clientes/$clientId': typeof AdminClientesClientIdRoute
  '/admin/contratos/novo': typeof AdminContratosNovoRoute
  '/admin/insights/precificacao': typeof AdminInsightsPrecificacaoRoute
  '/admin/propostas/nova': typeof AdminPropostasNovaRoute
  '/p/proposta/$token': typeof PPropostaTokenRoute
  '/admin/contratos/': typeof AdminContratosIndexRoute
  '/admin/propostas/': typeof AdminPropostasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/configurar-acesso': typeof ConfigurarAcessoRoute
  '/admin/clientes': typeof AdminClientesRouteWithChildren
  '/admin/dfc': typeof AdminDfcRoute
  '/admin/importar': typeof AdminImportarRoute
  '/admin/pendentes': typeof AdminPendentesRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/regras': typeof AdminRegrasRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/admin': typeof AdminIndexRoute
  '/admin/clientes/$clientId': typeof AdminClientesClientIdRoute
  '/admin/contratos/novo': typeof AdminContratosNovoRoute
  '/admin/insights/precificacao': typeof AdminInsightsPrecificacaoRoute
  '/admin/propostas/nova': typeof AdminPropostasNovaRoute
  '/p/proposta/$token': typeof PPropostaTokenRoute
  '/admin/contratos': typeof AdminContratosIndexRoute
  '/admin/propostas': typeof AdminPropostasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/configurar-acesso': typeof ConfigurarAcessoRoute
  '/admin/clientes': typeof AdminClientesRouteWithChildren
  '/admin/contratos': typeof AdminContratosRouteWithChildren
  '/admin/dfc': typeof AdminDfcRoute
  '/admin/importar': typeof AdminImportarRoute
  '/admin/pendentes': typeof AdminPendentesRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/propostas': typeof AdminPropostasRouteWithChildren
  '/admin/regras': typeof AdminRegrasRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/clientes/$clientId': typeof AdminClientesClientIdRoute
  '/admin/contratos/novo': typeof AdminContratosNovoRoute
  '/admin/insights/precificacao': typeof AdminInsightsPrecificacaoRoute
  '/admin/propostas/nova': typeof AdminPropostasNovaRoute
  '/p/proposta/$token': typeof PPropostaTokenRoute
  '/admin/contratos/': typeof AdminContratosIndexRoute
  '/admin/propostas/': typeof AdminPropostasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/portal'
    | '/configurar-acesso'
    | '/admin/categorias'
    | '/admin/usuarios'
    | '/admin/clientes'
    | '/admin/contratos'
    | '/admin/dfc'
    | '/admin/importar'
    | '/admin/pendentes'
    | '/admin/pipeline'
    | '/admin/propostas'
    | '/admin/regras'
    | '/admin/relatorios'
    | '/admin/servicos'
    | '/admin/'
    | '/admin/clientes/$clientId'
    | '/admin/contratos/novo'
    | '/admin/insights/precificacao'
    | '/admin/propostas/nova'
    | '/p/proposta/$token'
    | '/admin/contratos/'
    | '/admin/propostas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/portal'
    | '/configurar-acesso'
    | '/admin/categorias'
    | '/admin/usuarios'
    | '/admin/clientes'
    | '/admin/dfc'
    | '/admin/importar'
    | '/admin/pendentes'
    | '/admin/pipeline'
    | '/admin/regras'
    | '/admin/relatorios'
    | '/admin/servicos'
    | '/admin'
    | '/admin/clientes/$clientId'
    | '/admin/contratos/novo'
    | '/admin/insights/precificacao'
    | '/admin/propostas/nova'
    | '/p/proposta/$token'
    | '/admin/contratos'
    | '/admin/propostas'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/portal'
    | '/configurar-acesso'
    | '/admin/categorias'
    | '/admin/usuarios'
    | '/admin/clientes'
    | '/admin/contratos'
    | '/admin/dfc'
    | '/admin/importar'
    | '/admin/pendentes'
    | '/admin/pipeline'
    | '/admin/propostas'
    | '/admin/regras'
    | '/admin/relatorios'
    | '/admin/servicos'
    | '/admin/'
    | '/admin/clientes/$clientId'
    | '/admin/contratos/novo'
    | '/admin/insights/precificacao'
    | '/admin/propostas/nova'
    | '/p/proposta/$token'
    | '/admin/contratos/'
    | '/admin/propostas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRoute
  ConfigurarAcessoRoute: typeof ConfigurarAcessoRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminClientesRoute: typeof AdminClientesRouteWithChildren
  AdminContratosRoute: typeof AdminContratosRouteWithChildren
  AdminDfcRoute: typeof AdminDfcRoute
  AdminImportarRoute: typeof AdminImportarRoute
  AdminPendentesRoute: typeof AdminPendentesRoute
  AdminPipelineRoute: typeof AdminPipelineRoute
  AdminPropostasRoute: typeof AdminPropostasRouteWithChildren
  AdminRegrasRoute: typeof AdminRegrasRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminServicosRoute: typeof AdminServicosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminInsightsPrecificacaoRoute: typeof AdminInsightsPrecificacaoRoute
  PPropostaTokenRoute: typeof PPropostaTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/servicos': {
      id: '/admin/servicos'
      path: '/admin/servicos'
      fullPath: '/admin/servicos'
      preLoaderRoute: typeof AdminServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/admin/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/regras': {
      id: '/admin/regras'
      path: '/admin/regras'
      fullPath: '/admin/regras'
      preLoaderRoute: typeof AdminRegrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/propostas': {
      id: '/admin/propostas'
      path: '/admin/propostas'
      fullPath: '/admin/propostas'
      preLoaderRoute: typeof AdminPropostasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pipeline': {
      id: '/admin/pipeline'
      path: '/admin/pipeline'
      fullPath: '/admin/pipeline'
      preLoaderRoute: typeof AdminPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pendentes': {
      id: '/admin/pendentes'
      path: '/admin/pendentes'
      fullPath: '/admin/pendentes'
      preLoaderRoute: typeof AdminPendentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/importar': {
      id: '/admin/importar'
      path: '/admin/importar'
      fullPath: '/admin/importar'
      preLoaderRoute: typeof AdminImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dfc': {
      id: '/admin/dfc'
      path: '/admin/dfc'
      fullPath: '/admin/dfc'
      preLoaderRoute: typeof AdminDfcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contratos': {
      id: '/admin/contratos'
      path: '/admin/contratos'
      fullPath: '/admin/contratos'
      preLoaderRoute: typeof AdminContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/admin/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/admin/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configurar-acesso': {
      id: '/configurar-acesso'
      path: '/configurar-acesso'
      fullPath: '/configurar-acesso'
      preLoaderRoute: typeof ConfigurarAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/propostas/': {
      id: '/admin/propostas/'
      path: '/'
      fullPath: '/admin/propostas/'
      preLoaderRoute: typeof AdminPropostasIndexRouteImport
      parentRoute: typeof AdminPropostasRoute
    }
    '/admin/contratos/': {
      id: '/admin/contratos/'
      path: '/'
      fullPath: '/admin/contratos/'
      preLoaderRoute: typeof AdminContratosIndexRouteImport
      parentRoute: typeof AdminContratosRoute
    }
    '/p/proposta/$token': {
      id: '/p/proposta/$token'
      path: '/p/proposta/$token'
      fullPath: '/p/proposta/$token'
      preLoaderRoute: typeof PPropostaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/propostas/nova': {
      id: '/admin/propostas/nova'
      path: '/nova'
      fullPath: '/admin/propostas/nova'
      preLoaderRoute: typeof AdminPropostasNovaRouteImport
      parentRoute: typeof AdminPropostasRoute
    }
    '/admin/insights/precificacao': {
      id: '/admin/insights/precificacao'
      path: '/admin/insights/precificacao'
      fullPath: '/admin/insights/precificacao'
      preLoaderRoute: typeof AdminInsightsPrecificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contratos/novo': {
      id: '/admin/contratos/novo'
      path: '/novo'
      fullPath: '/admin/contratos/novo'
      preLoaderRoute: typeof AdminContratosNovoRouteImport
      parentRoute: typeof AdminContratosRoute
    }
    '/admin/clientes/$clientId': {
      id: '/admin/clientes/$clientId'
      path: '/$clientId'
      fullPath: '/admin/clientes/$clientId'
      preLoaderRoute: typeof AdminClientesClientIdRouteImport
      parentRoute: typeof AdminClientesRoute
    }
  }
}

interface AdminClientesRouteChildren {
  AdminClientesClientIdRoute: typeof AdminClientesClientIdRoute
}

const AdminClientesRouteChildren: AdminClientesRouteChildren = {
  AdminClientesClientIdRoute: AdminClientesClientIdRoute,
}

const AdminClientesRouteWithChildren = AdminClientesRoute._addFileChildren(
  AdminClientesRouteChildren,
)

interface AdminContratosRouteChildren {
  AdminContratosNovoRoute: typeof AdminContratosNovoRoute
  AdminContratosIndexRoute: typeof AdminContratosIndexRoute
}

const AdminContratosRouteChildren: AdminContratosRouteChildren = {
  AdminContratosNovoRoute: AdminContratosNovoRoute,
  AdminContratosIndexRoute: AdminContratosIndexRoute,
}

const AdminContratosRouteWithChildren = AdminContratosRoute._addFileChildren(
  AdminContratosRouteChildren,
)

interface AdminPropostasRouteChildren {
  AdminPropostasNovaRoute: typeof AdminPropostasNovaRoute
  AdminPropostasIndexRoute: typeof AdminPropostasIndexRoute
}

const AdminPropostasRouteChildren: AdminPropostasRouteChildren = {
  AdminPropostasNovaRoute: AdminPropostasNovaRoute,
  AdminPropostasIndexRoute: AdminPropostasIndexRoute,
}

const AdminPropostasRouteWithChildren = AdminPropostasRoute._addFileChildren(
  AdminPropostasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRoute,
  ConfigurarAcessoRoute: ConfigurarAcessoRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminClientesRoute: AdminClientesRouteWithChildren,
  AdminContratosRoute: AdminContratosRouteWithChildren,
  AdminDfcRoute: AdminDfcRoute,
  AdminImportarRoute: AdminImportarRoute,
  AdminPendentesRoute: AdminPendentesRoute,
  AdminPipelineRoute: AdminPipelineRoute,
  AdminPropostasRoute: AdminPropostasRouteWithChildren,
  AdminRegrasRoute: AdminRegrasRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminServicosRoute: AdminServicosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminInsightsPrecificacaoRoute: AdminInsightsPrecificacaoRoute,
  PPropostaTokenRoute: PPropostaTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
